apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ramanijadala/backend:v1
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "book.rds.com"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "password123"